default: &default
  adapter: postgresql
  encoding: utf8
  database: vote
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: vote

test:
  <<: *default
  database: vote

production:
  <<: *default
  database: vote
